pluginName: ${pluginName}
description: ${description}
version: ${version}
coreVersion: ${coreVersion}
procedures:
  - name: Sample Procedure
    description: Sample procedure description
    hasConfig: true
    parameters:
      - name: applicationPath
        description: Path to the application
        type: entry
        required: true
        label: Application Path
    outputParameters:
      deployed: JSON representation of the deployed application
    # Steps are not defined so we assume that this is one-step procedure with a single step named Deploy
    shell: ec-groovy
